---
# The RPM packaging is only launched if a tag is present. The tag spec is below.
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: 'packaging/docker-rpmbuild'
    ref: master
    file: '/templates/rpmbuild.yml'

stages:
  - validate
  - rpmbuild-generate-ci-jobs
  - rpmbuild-trigger-ci-jobs

default:
  image: docker.artifactory.booking.com/projects/golang/golang-ci:1.23.4

variables:
  RPMBUILD_CENTOS_VERSIONS: "7 8 9"
  RPMBUILD_TARGET_REPO: /yum/booking.com/$${CENTOS_VER}/graphite
  # The tag must match the timestamp format of 'ddmmyyyy.hhmmss'.
  # You can generate its value with the date +"%d%m%Y.%H%M%S" command.
  RPMBUILD_TAG_MATCH: "^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\\.[0-9][0-9][0-9][0-9][0-9][0-9]$"

# lint:
#   stage: validate
#   before_script:
#   - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.56.2
#   script:
#   - make lint
#   tags:
#   - docker

# NOTE: This is a throw-away build; the artifact is not used anywhere.
build:
  tags:
  - docker
  stage: validate
  script:
  - make build
