---
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - validate
  - rpmbuild-generate-ci-jobs
  - rpmbuild-trigger-ci-jobs

default:
  image: docker.artifactory.booking.com/projects/golang/golang-ci:latest

variables:
  RPMBUILD_CENTOS_VERSIONS: "7 8"
  RPMBUILD_TARGET_REPO: /yum/booking-extras/$${CENTOS_VER}/x86_64/RPMS
  RPMBUILD_TAG_MATCH: "^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\\.[0-9][0-9][0-9][0-9][0-9][0-9]$"

lint:
  stage: validate
  before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.45.0
  script:
  - make lint
  tags:
  - docker

# NOTE: This is a throw-away build; the artifact is not used anywhere.
build:
  tags:
  - docker
  stage: validate
  script:
  - make build

# Enable docker-rpmbuild-pipeline
# https://gitlab.booking.com/packaging/docker-rpmbuild
#
include:
  - project: 'packaging/docker-rpmbuild'
    ref: master
    file: '/templates/rpmbuild.yml'
