---
# The RPM packaging is only launched if a tag is present. The tag spec is below.
include:
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"
  - project: ${GITLAB_BOOKING_BASE}packaging/docker-rpmbuild
    ref: master
    file: "/templates/rpmbuild.yml"

stages:
  - validate
  - rpmbuild-generate-ci-jobs
  - rpmbuild-trigger-ci-jobs

default:
  # For more info: https://gitlab.booking.com/go/ci-cd/tree/master/golang-ci
  image: docker.jfrog.booking.com/projects/golang/golang-ci:1.25-ci-v2

variables:
  RPMBUILD_CENTOS_VERSIONS: "7 8 9"
  RPMBUILD_TARGET_REPO: /yum/booking.com/$${CENTOS_VER}/graphite
  # The tag must match the timestamp format of 'yyyymmdd.hhmmss'.
  # You can generate its value with the date +"%Y%m%d.%H%M%S" command.
  RPMBUILD_TAG_MATCH: "^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\\.[0-9][0-9][0-9][0-9][0-9][0-9]$"
  RPMBUILD_ENABLE_REPOS: yum-repositories-booking-go
  RPMBUILD_DISABLE_MODULES_8: go-toolset
  RPMBUILD_DISABLE_MODULES_7: go-toolset

# lint:
#   stage: validate
#   before_script:
#   - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.56.2
#   script:
#   - make lint
#   tags:
#   - docker

# NOTE: This is a throw-away build; the artifact is not used anywhere.
build:
  tags:
    - docker
  stage: validate
  script:
    - make build
