version: "3"

services:
  go-carbon-0:
    build:
      dockerfile: docker/go-carbon/Dockerfile
      context: .

  go-carbon-1:
    build:
      dockerfile: docker/go-carbon/Dockerfile
      context: .

  carbonapi:
    build:
      dockerfile: docker/carbonapi/Dockerfile
      context: .
    ports:
      - "8081:8081"
    links:
      - zipper

  zipper:
    build:
      dockerfile: docker/zipper/Dockerfile
      context: .
    ports:
      - "7000:7000"
      - "8000:8000"
    links:
      - go-carbon-0
      - go-carbon-1

  nanotube:
    build:
      dockerfile: docker/nanotube/Dockerfile
      context: .
    ports:
      - "2003:2003"
