ClustersConfig = "config/clusters.toml"
RulesConfig = "config/rules.toml"

# Launch NT as a k8s daemonset forwarding metrics from pods. kubeNT!
K8sMode = true
# Pods to inject for TCP listening on selected pods. Metics sent to that port will be forwarded
# to the running daemon-set.
K8sInjectPortTCP = 2003
# Label to filter pods on. Only labeled pods running on the same node as NT daemon-set will get
# the port injection.
# Empty string means no filtering on label.
K8sFilterLabel = ""
K8sContainerd = true

TargetPort = 2004

ListenTCP = ":2003"
ListenUDP = ""

MainQueueSize = 100000
HostQueueSize = 50000

WorkerPoolSize = 50

IncomingConnIdleTimeoutSec = 90
SendTimeoutSec = 5
OutConnTimeoutSec = 5
TermTimeoutSec = 10

TCPOutBufSize = 4096
TCPOutBufFlushPeriodSec = 2

MaxHostReconnectPeriodMs = 5000
HostReconnectPeriodDeltaMs = 10

NormalizeRecords = true
LogSpecialRecords = false

PprofPort = 6000
PromPort = 9090

HostQueueLengthBucketFactor = 3.0
HostQueueLengthBuckets = 10
ProcessingDurationBucketFactor = 2.0
ProcessingDurationBuckets = 10
