# E.g.
# In: abcxxx
# Out: cdexxx
[[rewrite]]
    from = 'abc'
    to = 'cde'

# E.g.
# In: xxx.A99.foo.bar
# Out:
# - xxx.foo.bar.A99
# - xxx.A99.foo.bar
[[rewrite]]
    from = '^xxx.([A-Za-z0-9_-]+).(.*)'
    to = 'xxx.$2.$1'
    copy = true

