apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
  namespace: default
  labels:
    app: sender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: sender
          imagePullPolicy: IfNotPresent
