// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcstreamer

import (
	context "context"
	v1 "github.com/bookingcom/nanotube/pkg/opentelemetry/proto/metrics/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamerClient is the client API for Streamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamerClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Streamer_StreamClient, error)
}

type streamerClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamerClient(cc grpc.ClientConnInterface) StreamerClient {
	return &streamerClient{cc}
}

func (c *streamerClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Streamer_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Streamer_ServiceDesc.Streams[0], "/Streamer/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamerStreamClient{stream}
	return x, nil
}

type Streamer_StreamClient interface {
	Send(*v1.Metric) error
	CloseAndRecv() (*Result, error)
	grpc.ClientStream
}

type streamerStreamClient struct {
	grpc.ClientStream
}

func (x *streamerStreamClient) Send(m *v1.Metric) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamerStreamClient) CloseAndRecv() (*Result, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamerServer is the server API for Streamer service.
// All implementations must embed UnimplementedStreamerServer
// for forward compatibility
type StreamerServer interface {
	Stream(Streamer_StreamServer) error
	mustEmbedUnimplementedStreamerServer()
}

// UnimplementedStreamerServer must be embedded to have forward compatible implementations.
type UnimplementedStreamerServer struct {
}

func (UnimplementedStreamerServer) Stream(Streamer_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedStreamerServer) mustEmbedUnimplementedStreamerServer() {}

// UnsafeStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamerServer will
// result in compilation errors.
type UnsafeStreamerServer interface {
	mustEmbedUnimplementedStreamerServer()
}

func RegisterStreamerServer(s grpc.ServiceRegistrar, srv StreamerServer) {
	s.RegisterService(&Streamer_ServiceDesc, srv)
}

func _Streamer_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamerServer).Stream(&streamerStreamServer{stream})
}

type Streamer_StreamServer interface {
	SendAndClose(*Result) error
	Recv() (*v1.Metric, error)
	grpc.ServerStream
}

type streamerStreamServer struct {
	grpc.ServerStream
}

func (x *streamerStreamServer) SendAndClose(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamerStreamServer) Recv() (*v1.Metric, error) {
	m := new(v1.Metric)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Streamer_ServiceDesc is the grpc.ServiceDesc for Streamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Streamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Streamer",
	HandlerType: (*StreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Streamer_Stream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/grpcstreamer/streamer.proto",
}
