on: [push, pull_request]
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.23.x, 1.24.x, tip ]
    steps:
      - name: Set up Go stable
        if: matrix.go-version != 'tip'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up Go tip
        if: matrix.go-version == 'tip'
        run: |
          curl -o go.tar.gz -L \
          https://github.com/AlekSi/golang-tip/releases/download/tip/master.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          sudo ln -s /usr/local/go/bin/* /usr/local/bin/
          /usr/local/bin/go version
          echo "PATH=$HOME/go/bin:$HOME/sdk/gotip/bin/:$PATH" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v5
      - name: golangci-lint
        if: matrix.go-version == '1.24.x'
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
      - name: govulncheck
        if: matrix.go-version == '1.24.x'
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true
          go-package: ./...
      - name: test
        run: make test
